server:
  port: 5050
  forward-headers-strategy: framework

logging:
  level:
    "[org.springframework.security]": DEBUG

frontend:
  url: ${FRONTEND_URL:http://localhost:3030}

app:
  storage:
    avatar-dir: /usr/app/data/uploads

spring:
  application:
    name: apijava-auth
  datasource:
    url: jdbc:h2:file:/usr/app/data/auth_db
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        "[format_sql]": true
  sql:
    init:
      mode: always
      data-locations: classpath:import.sql

  # OAuth2 Stubs (These must be overridden by environment variables in production)
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH2_GOOGLE_CLIENT_ID:tu-client-id-google}
            client-secret: ${OAUTH2_GOOGLE_CLIENT_SECRET:tu-client-secret-google}
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

jwt:
  secret: super-secret-key-for-nexuszen-auth-that-must-be-long-enough-for-hs256-signature-12345
  expiration: 86400000
